export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_START = "USER_AUTHENTICATION_START";
export const USER_AUTHENTICATION_FAILURE = "USER_AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";